name: Test and Release

env:
  # Sync with .changeset/config.json:baseBranch
  MAIN_REF: refs/heads/main

on:
  push:
    branches: ["**"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

# Publish to npm with OIDC
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # for npx publish
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build

      - name: Test packages
        run: bun run test

      - name: Capture new release versions
        if: ${{ github.ref == env.MAIN_REF }}
        run: |
          if bunx @changesets/cli status --output=release.json; then
            echo "RELEASE=Version $(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"
            rm release.json
          fi

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == env.MAIN_REF }}
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
          title: ${{ env.RELEASE }}
          commit: ${{ env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
